apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg://user:password@postgres.default.svc.cluster.local:5432/house_stats
  REDIS_URL: redis://redis-server.default.svc.cluster.local:6379/0
  SECRET_KEY: put-key-here
  STRIPE_API_TOKEN: stripe-token
  JWT_ALGORITHM: HS256