name: Pytest

on:
  push:
    paths:
      - "web-api/**"
  pull_request:
    paths:
      - "web-api/**"


jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: house
          POSTGRES_PASSWORD: househousehouse
          POSTGRES_DB: house_stats
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    strategy:
      matrix:
        python-version: ["3.13"]

    defaults:
      run:
        working-directory: web-api

    env:
      DATABASE_URL: "postgresql+psycopg2://house:househousehouse@localhost/house_stats"
      JWT_ALGORITHM: "HS256"
      SECRET_KEY: "12f6240d3c24ee8b32df96fa21c91c5fc52e94343f1d6bed4f571867b063ef66"
      STRIPE_API_TOKEN: {{secrets.STRIPE_TEST_API_TOKEN}}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev

      - name: Run pytest
        run: |
          uv run pytest
